access_control:
  files:
    'policies/gcp/compute-instance.rego': ['team:sre']

engine:
  name: tofu

indexer:
  enabled: true

hooks:
  plan:
    post:
      - type: run
        cmd: ['conftest', 'test', '-o', 'table', '${TERRATEAM_TMPDIR}/infracost/infracost.json', '--policy', '$TERRATEAM_ROOT/policies/gcp/compute-instance.rego']

workflows:
  - tag_query: ""
    plan:
      - type: run
        cmd: ['${TERRATEAM_TF_CMD}', 'fmt', '-check']
      - type: run
        cmd: ['${TERRATEAM_TF_CMD}', 'validate']
      - type: init
      - type: plan

cost_estimation:
  enabled: true

apply_requirements:
  checks:
    - tag_query: "dir:dev"
      approved:
        enabled: false
    - tag_query: "dir:production"
      approved:
        enabled: true
        any_of: ["team:sre"]
        any_of_count: 1

drift:
  enabled: true
  schedule: hourly
