engine:
  name: tofu

indexer:
  enabled: true

hooks:
  plan:
    post:
      - type: run
        cmd: ['conftest', 'test', '-o', 'table', '${TERRATEAM_TMPDIR}/infracost/infracost.json', '--policy', '$TERRATEAM_ROOT/policies/gcp/compute-instance.rego']
        capture_output: true

workflows:
  - tag_query: "dir:staging"
    plan:
      - type: run
        cmd: ['${TERRATEAM_TF_CMD}', 'fmt']
      - type: run
        cmd: ['${TERRATEAM_TF_CMD}', 'validate']
      - type: init
      - type: plan
  - tag_query: "dir:production"
    plan:
      - type: run
        cmd: ['${TERRATEAM_TF_CMD}', 'fmt']
      - type: run
        cmd: ['${TERATEAM_TF_CMD}', 'validate']
      - type: init
      - type: plan

cost_estimation:
  enabled: true

apply_requirements:
  checks:
    - tag_query: "dir:staging"
      approved:
        enabled: true
        any_of_count: 1
    - tag_query: "dir:production"
      approved:
        enabled: true
        any_of: ["team:sre"]
        any_of_count: 1

drift:
  enabled: true
  schedule: hourly
